### PR TITLE
Implement SNMPtrap delivery controls

### PR DESCRIPTION
**Pull request by leifmadsen**
Implement ability to override the default values for the SNMPtrap
alertmanager receiver via prometheus-webhook-snmp component.

Closes: STF-559
Depends-on: https://github.com/infrawatch/prometheus-webhook-snmp/pull/14

### CODE REVIEW

**Comment by leifmadsen** [comment]
test

**Comment by leifmadsen** [comment]
Marked this as "do not merge" as I've made the changes locally but have no yet imported them to a working environment for building and testing.

**Comment by elfiesmelfie** [comment]
test

**Comment by leifmadsen** [comment]
test

**Comment by leifmadsen** [comment]
Performed another deployment testing a few of the new changes in this PR with the following results.

Deployment with this command:

```
ansible-playbook -e namespace="service-telemetry" -e __local_build_enabled=true -e __service_telemetry_snmptraps_enabled=true -e __service_telemetry_storage_ephemeral_enabled=false -e prometheus_webhook_snmp_branch="stf-559/configurable-snmp-webhook-params" -e __service_telemetry_snmptraps_community=testing -e __service_telemetry_snmptraps_target=192.168.255.255 -e __service_telemetry_snmptraps_retries=7 -e __service_telemetry_snmptraps_port=6200 -e __service_telemetry_snmptraps_timeout=5 -e __service_telemetry_trap_default_severity=warning ./build/run-ci.yaml
```

Results in this spec (partial):

```
        "spec": {
            "alerting": {
                "alertmanager": {
                    "receivers": {
                        "snmpTraps": {
                            "alertOidLabel": "oid",
                            "community": "testing",
                            "enabled": true,
                            "port": 6200,
                            "retries": 7,
                            "target": "192.168.255.255",
                            "timeout": 5,
                            "trapDefaultOid": "1.3.6.1.4.1.50495.15.1.2.1",
                            "trapDefaultSeverity": "",
                            "trapOidPrefix": "1.3.6.1.4.1.50495.15"
```

And everything completed:

```
        "* [info] CI Build complete. You can now run tests."
    ]
}

PLAY RECAP ***************************************************************************************************************************************************************************************************************************************
localhost                  : ok=114  changed=46   unreachable=0    failed=0    skipped=29   rescued=0    ignored=0   
```

Everything is running:

```
oc get pods
NAME                                                      READY   STATUS      RESTARTS   AGE
alertmanager-default-0                                    3/3     Running     0          2m44s
default-cloud1-ceil-event-smartgateway-556d896669-vp5bp   2/2     Running     0          119s
default-cloud1-ceil-meter-smartgateway-5d5dd9965c-qwxqd   3/3     Running     0          2m12s
default-cloud1-coll-event-smartgateway-64b4786966-cw4rw   2/2     Running     0          2m1s
default-cloud1-coll-meter-smartgateway-9745cd6c6-qgk2s    3/3     Running     0          2m12s
default-cloud1-sens-meter-smartgateway-84f55b998c-247vr   3/3     Running     0          2m9s
default-interconnect-845c4b647c-7x84w                     1/1     Running     0          3m10s
default-snmp-webhook-7c9f5b769b-hzmwq                     1/1     Running     0          2m52s
elastic-operator-88bf4556f-rjdj7                          1/1     Running     0          11m
elasticsearch-es-default-0                                1/1     Running     0          2m34s
interconnect-operator-99dc7f8d8-4fgt9                     1/1     Running     0          11m
prometheus-default-0                                      3/3     Running     0          98s
prometheus-operator-6f75dffbf4-vxz7l                      1/1     Running     0          11m
prometheus-webhook-snmp-2-build                           0/1     Completed   0          5m39s
service-telemetry-operator-2-build                        0/1     Completed   0          11m
service-telemetry-operator-5c4759bb6c-twnmg               1/1     Running     0          3m41s
sg-bridge-2-build                                         0/1     Completed   0          6m45s
sg-core-2-build                                           0/1     Completed   0          10m
smart-gateway-operator-2-build                            0/1     Completed   0          10m
smart-gateway-operator-58d6449bb9-56cxz                   1/1     Running     0          3m48s
```

Verified everything is passed through to the changes in the same-named branch on prometheus-webhook-snmp:

```
oc logs -f default-snmp-webhook-7c9f5b769b-hzmwq
DEBUG:prometheus_webhook_snmp.utils:Configuration settings: {"debug": true, "snmp_host": "192.168.255.255", "snmp_port": 6200, "snmp_community": "testing", "snmp_retries": 7, "snmp_timeout": 6200, "alert_oid_label": "oid", "trap_oid_prefix": "1.3.6.1.4.1.50495.15", "trap_default_oid": "1.3.6.1.4.1.50495.15.1.2.1", "trap_default_severity": "", "host": "0.0.0.0", "port": 9099, "metrics": false, "cert": "", "key": ""}
INFO:cherrypy.error:[14/Feb/2023:21:30:56] ENGINE Listening for SIGTERM.
INFO:cherrypy.error:[14/Feb/2023:21:30:56] ENGINE Listening for SIGHUP.
INFO:cherrypy.error:[14/Feb/2023:21:30:56] ENGINE Listening for SIGUSR1.
INFO:cherrypy.error:[14/Feb/2023:21:30:56] ENGINE Bus STARTING
INFO:cherrypy.error:[14/Feb/2023:21:30:56] ENGINE Serving on http://0.0.0.0:9099
INFO:cherrypy.error:[14/Feb/2023:21:30:56] ENGINE Bus STARTED
```

**Comment by leifmadsen** [comment]
Confirmation that the UI displays appropriately per CRD and CR in the bundle:

image

**Review by csibbitt — APPROVED** [review]

**Comment by leifmadsen** [comment]
test

**Comment by leifmadsen** [comment]
Got an approval from Chris a while ago and now Emma has helped get all the tests passing. I am merging this down as I don't expect any further reviews.

**Pull request merged**
