### PR TITLE
Revert cert-manager channel to "tech-preview"

### PR DESCRIPTION
**Pull request by vkmc**
We recently changed the channel being used to retrieve cert-manager from "tech-preview" to "stable-v1"

Since we only support tech-preview for up to STF 1.5.2, we should stick to test using that version

### CODE REVIEW

**Review by csibbitt — APPROVED** [review]

**Review by leifmadsen — APPROVED** [review]

**Comment by leifmadsen** [comment]
test

**Comment by vkmc** [comment]
test

**Comment by vkmc** [comment]
test

**Comment by vkmc** [comment]
test

**Comment by vkmc** [comment]
For some reason CI for 410 is not updating the status, but since this change doesn't affect it, it should be ok. Retriggered jobs to see if the status is properly updated this time. If not, I will proceed to merge anyways.

**Pull request merged**
