### PR TITLE
Fix branch co-ordination in stf-run-ci

### PR DESCRIPTION
**Pull request by csibbitt**
I think it got broken by an oops recently[1].

Since that change, working_branch (`branch` at that point) is never used because version_branches.sgo has a default value.

This breaks the branch co-ordination in Jenkins[2] and in local testing[3].

[1] https://github.com/infrawatch/service-telemetry-operator/pull/512/files#diff-c073fe1e346d08112920aa0bbc8a7453bbd3032b7a9b09ae8cbc70df4db4ea2dR19
[2] https://github.com/infrawatch/service-telemetry-operator/blob/0f94fd577617aee6a85fc4141f98ebdfc49a9f92/Jenkinsfile#L157
[3] https://github.com/infrawatch/service-telemetry-operator/blob/0f94fd577617aee6a85fc4141f98ebdfc49a9f92/README.md?plain=1#L62

### CODE REVIEW

**Review by leifmadsen — APPROVED** [review]
Looks about right to me. Could there be a DNM change in SGO or something to test the coordination here with a same-named branch?

**Comment by csibbitt** [comment]
Before this change, `working_branch` is ignored, and the SGO repo is checked out from the master branch

```
$ rm -Rf working/                                                                                                                              
$ git rev-parse --abbrev-ref HEAD
csibbitt/better-auth-sars

$ ansible-playbook --extra-vars __local_build_enabled=true --extra-vars working_branch="$(git rev-parse --abbrev-ref HEAD)" --extra-vars __service_telemetry_snmptraps_enabled=true --extra-vars __service_telemetry_storage_ephemeral_enabled=true --extra-vars __service_telemetry_observability_strategy=use_redhat ./run-ci.yaml
[...]
TASK [stf-run-ci : Try cloning same-named branch or override branch from SGO repository] ************************************************************************************************
changed: [localhost]
^C [ERROR]: User interrupted execution

$ cd working/smart-gateway-operator/
$ git status
On branch master
Your branch is up to date with 'origin/master'.
nothing to commit, working tree clean
```

After the change it checks out the matching branch
```
$ rm -Rf working/
$ git merge csibbitt/STF-1665_fix-working_branch
Merge made by the 'ort' strategy.
 build/stf-run-ci/tasks/clone_repos.yml | 8 ++++----
 build/stf-run-ci/tasks/main.yml        | 1 -
 2 files changed, 4 insertions(+), 5 deletions(-)

$ ansible-playbook --extra-vars __local_build_enabled=true --extra-vars working_branch="$(git rev-parse --abbrev-ref HEAD)" --extra-vars __service_telemetry_snmptraps_enabled=true --extra-vars __service_telemetry_storage_ephemeral_enabled=true --extra-vars __service_telemetry_observability_strategy=use_redhat ./run-ci.yaml
[...]
TASK [stf-run-ci : Try cloning same-named branch or override branch from SGO repository] ************************************************************************************************
changed: [localhost]
^C [ERROR]: User interrupted execution

$ cd working/smart-gateway-operator/
$ git status
On branch csibbitt/better-auth-sars
Your branch is up to date with 'origin/csibbitt/better-auth-sars'.
nothing to commit, working tree clean
```

**Comment by csibbitt** [comment]
> Looks about right to me. Could there be a DNM change in SGO or something to test the coordination here with a same-named branch?

I just put up a local test. Once we merge it I'll also test it in Jenkins on this PR https://github.com/infrawatch/service-telemetry-operator/pull/553 which requires the co-ordination in order to pass smoketests

**Review by elfiesmelfie — APPROVED** [review]
Looks sensible to me.

Your plan to test against an in-flight PR sounds good too

**Pull request merged**
