### PR TITLE
[zuul] Add a job that does a local build and deploys an STF object

### PR DESCRIPTION
**Pull request by elfiesmelfie**
This job replicates the job in Jenkinsfile

Depends-On: https://github.com/infrawatch/service-telemetry-operator/pull/478
Depends-On: https://github.com/infrawatch/service-telemetry-operator/pull/484
Depends-On: https://github.com/infrawatch/service-telemetry-operator/pull/496
Depends-On: https://github.com/infrawatch/service-telemetry-operator/pull/498

### CODE REVIEW

**Review by csibbitt — APPROVED** [review]

**Review by vkmc — APPROVED** [review]
LGTM, thanks Emma!

**Comment by elfiesmelfie** [comment]
recheck

**Comment by elfiesmelfie** [comment]
recheck

https://github.com/infrawatch/service-telemetry-operator/pull/484 has merged

**Comment by elfiesmelfie** [comment]
recheck

time out on creating the Elastic Search object

**Comment by elfiesmelfie** [comment]
recheck

**Comment by elfiesmelfie** [comment]
recheck

**Review by leifmadsen — APPROVED** [review]

**Comment by leifmadsen** [comment]
Oh snap! And even 4.14 jenkins passed! Let's gooooo!

**Pull request merged**
