### PR TITLE
Update CI automation

### PR DESCRIPTION
**Pull request by leifmadsen**
Update the CI automation to account for new bundle format within
the Smart Gateway Operator and Service Telemetry Operator repositories.

### CODE REVIEW

**Comment by leifmadsen** [comment]
Oops I should have done this as part of the bundle migration...

**Comment by leifmadsen** [comment]
So far untested. CI system is currently down, so will need to remember how to run a local test :)

**Comment by leifmadsen** [comment]
[Migrate Operators to bundle packaging format and distribution](https://trello.com/c/xfwIfs7Z/1065-migrate-operators-to-bundle-packaging-format-and-distribution)

**Review by pleimer — APPROVED** [review]

**Pull request merged**
