### PR TITLE
[DNM] Testing only

### PR DESCRIPTION
**Pull request by leifmadsen**
Test PR to help validate https://github.com/infrawatch/prometheus-webhook-snmp/pull/10

### CODE REVIEW

**Comment by leifmadsen** [comment]
test

**Comment by leifmadsen** [comment]
test

**Comment by leifmadsen** [comment]
Seems as if the CI system isn't picking up the request with `test`. If someone has a few mins and help kick this it'd be very much appreciated.

**Comment by elfiesmelfie** [comment]
You need to change one of the files that matches this: egrep 'build/.*|deploy/.*|roles/.*|tests/smoketest/.*|Makefile|watches.yaml|Jenkinsfile'
Otherwise, tests are skipped.

**Comment by leifmadsen** [comment]
test

**Comment by leifmadsen** [comment]
test

**Comment by leifmadsen** [comment]
test

**Comment by leifmadsen** [comment]
Well that's interesting... moving the check a bit later in the process seems to have caused this to pass (somewhat expected). What does seem strange is the order in which the outputs show up. A bit more investigation is necessary here to figure out what is going on.

**Comment by leifmadsen** [comment]
```
+ OCP_PROJECT=pr-379-5
+ ./tests/smoketest/smoketest.sh
Already on project "pr-379-5" on server "https://172.30.0.1:443".
*** [INFO] Working in project pr-379-5
*** [INFO] Getting ElasticSearch authentication password
*** [INFO] Getting Prometheus authentication password
*** [INFO] Setting namepsace for collectd-sensubility config
*** [INFO] Creating configmaps...
Error from server (NotFound): configmaps "stf-smoketest-healthcheck-log" not found
Error from server (NotFound): configmaps "stf-smoketest-collectd-config" not found
Error from server (NotFound): configmaps "stf-smoketest-sensubility-config" not found
Error from server (NotFound): configmaps "stf-smoketest-collectd-entrypoint-script" not found
Error from server (NotFound): configmaps "stf-smoketest-ceilometer-publisher" not found
Error from server (NotFound): configmaps "stf-smoketest-ceilometer-entrypoint-script" not found
Error from server (NotFound): jobs.batch "stf-smoketest" not found
configmap/stf-smoketest-healthcheck-log created
configmap/stf-smoketest-collectd-config created
configmap/stf-smoketest-sensubility-config created
configmap/stf-smoketest-collectd-entrypoint-script created
configmap/stf-smoketest-ceilometer-publisher created
configmap/stf-smoketest-ceilometer-entrypoint-script created
*** [INFO] Creating smoketest jobs...
No resources found
job.batch/stf-smoketest-smoke1 created
*** [INFO] Triggering an alertmanager notification...
pod/curl created
*** [INFO] Waiting on job/stf-smoketest-smoke1...
job.batch/stf-smoketest-smoke1 condition met
pod "curl" deleted
*** [DEBUG] Current value of SNMP_WEBHOOK_STATUS: 1
*** [INFO] Showing oc get all...

[...]

*** [INFO] Logs from snmp webhook...
DEBUG:prometheus_webhook_snmp.utils:Configuration settings: {"debug": true, "snmp_host": "192.168.24.254", "snmp_port": 162, "snmp_community": "public", "snmp_retries": 5, "snmp_timeout": 1, "alert_oid_label": "oid", "trap_oid_prefix": "1.3.6.1.4.1.50495.15", "trap_default_oid": "1.3.6.1.4.1.50495.15.1.2.1", "trap_default_severity": "", "host": "0.0.0.0", "port": 9099, "metrics": false, "cert": "", "key": ""}
INFO:cherrypy.error:[17/Oct/2022:17:17:39] ENGINE Listening for SIGTERM.
INFO:cherrypy.error:[17/Oct/2022:17:17:39] ENGINE Listening for SIGHUP.
INFO:cherrypy.error:[17/Oct/2022:17:17:39] ENGINE Listening for SIGUSR1.
INFO:cherrypy.error:[17/Oct/2022:17:17:39] ENGINE Bus STARTING
INFO:cherrypy.error:[17/Oct/2022:17:17:39] ENGINE Serving on http://0.0.0.0:9099
INFO:cherrypy.error:[17/Oct/2022:17:17:39] ENGINE Bus STARTED
DEBUG:prometheus_webhook_snmp.utils:Receiving notification: {'receiver': 'snmp_wh', 'status': 'firing', 'alerts': [{'status': 'firing', 'labels': {'alertname': 'Testalert1'}, 'annotations': {}, 'startsAt': '2022-10-17T17:18:31.491354962Z', 'endsAt': '0001-01-01T00:00:00Z', 'generatorURL': '', 'fingerprint': '89b9adc4eabe71e7'}], 'groupLabels': {}, 'commonLabels': {'alertname': 'Testalert1'}, 'commonAnnotations': {}, 'externalURL': 'http://alertmanager-default-0:9093', 'version': '4', 'groupKey': '{}:{}', 'truncatedAlerts': 0}
DEBUG:prometheus_webhook_snmp.utils:Sending SNMP trap: {'oid': '1.3.6.1.4.1.50495.15.1.2.1', 'alertname': 'Testalert1', 'status': 'firing', 'severity': '', 'instance': None, 'job': None, 'description': None, 'labels': {}, 'timestamp': 1666027111, 'rawdata': {'status': 'firing', 'labels': {}, 'annotations': {}, 'startsAt': '2022-10-17T17:18:31.491354962Z', 'endsAt': '0001-01-01T00:00:00Z', 'generatorURL': '', 'fingerprint': '89b9adc4eabe71e7'}}
INFO:cherrypy.access.139740807155552:10.128.1.165 - - [17/Oct/2022:17:19:01] "POST / HTTP/1.1" 200 - "" "Alertmanager/0.21.0"

*** [INFO] Logs from alertmanager...
level=info ts=2022-10-17T17:17:46.699Z caller=main.go:216 msg="Starting Alertmanager" version="(version=0.21.0, branch=HEAD, revision=4c6c03ebfe21009c546e4d1e9b92c371d67c021d)"
level=info ts=2022-10-17T17:17:46.699Z caller=main.go:217 build_context="(go=go1.14.4, user=root@dee35927357f, date=20200617-08:54:02)"
level=info ts=2022-10-17T17:17:46.730Z caller=coordinator.go:119 component=configuration msg="Loading configuration file" file=/etc/alertmanager/config/alertmanager.yaml
level=info ts=2022-10-17T17:17:46.730Z caller=coordinator.go:131 component=configuration msg="Completed loading of configuration file" file=/etc/alertmanager/config/alertmanager.yaml
level=info ts=2022-10-17T17:17:46.733Z caller=main.go:485 msg=Listening address=127.0.0.1:9093
level=info ts=2022-10-17T17:17:48.670Z caller=coordinator.go:119 component=configuration msg="Loading configuration file" file=/etc/alertmanager/config/alertmanager.yaml
level=info ts=2022-10-17T17:17:48.671Z caller=coordinator.go:131 component=configuration msg="Completed loading of configuration file" file=/etc/alertmanager/config/alertmanager.yaml

*** [INFO] Cleanup resources...
job.batch "stf-smoketest-smoke1" deleted

*** [DEBUG] Working against SNMP_WEBHOOK_POD: default-snmp-webhook-696f4fd5cf-6qmtp
DEBUG:prometheus_webhook_snmp.utils:Sending SNMP trap: {'oid': '1.3.6.1.4.1.50495.15.1.2.1', 'alertname': 'Testalert1', 'status': 'firing', 'severity': '', 'instance': None, 'job': None, 'description': None, 'labels': {}, 'timestamp': 1666027111, 'rawdata': {'status': 'firing', 'labels': {}, 'annotations': {}, 'startsAt': '2022-10-17T17:18:31.491354962Z', 'endsAt': '0001-01-01T00:00:00Z', 'generatorURL': '', 'fingerprint': '89b9adc4eabe71e7'}}
*** [DEBUG] Current value of SNMP_WEBHOOK_STATUS: 0
*** [SUCCESS] Smoke test job completed successfully
```

**Pull request closed without merging**
