### PR TITLE
Use hostname -s to create unique cluster hostnames

### PR DESCRIPTION
**Pull request by leifmadsen**
Just playing around with something to help with multi-cluster testing and set up. I have a cloud that stood up using this, but not verified if it looks as expected in the Grafana output and labeling etc.

### CODE REVIEW

**Comment by pleimer** [comment]
I just wanted to see it work 😠 Looks like it needs to be rebased on master

**Comment by leifmadsen** [comment]
I tested this recently. Merged most recent master branch in to here too. There is no functional test for these changes. I will provide test output shortly (relative to OpenStack installation time) since I'm about to run a new deployment now.

**Comment by leifmadsen** [comment]
Definitely no issues running with this now. This will be ready for merge today I hope. I'm planning to point this cloud at an STF instance and will verify that I see some sort of unique hostname vs `redhat.local`. If that's the case, I'll merge this down.

(I know the `AMQP_HOST` has no effect here, but this is how I ran it, and is what I do just so that I don't forget the syntax that I want when I want to re-run the cloud deployment with STF enabled :) )

```
ENABLE_STF_CONNECTORS=false LIBVIRT_DISKPOOL="/home/libvirt/images" AMQP_HOST=default-interconnect-5671-service-telemetry.apps.stf.cloudops.psi.redhat.com ./infrared-openstack.sh

[...]

TASK [workaround heat-engine pcs start timeout rhbz#1306633 rhbz#1366141 rhbz#1377788] *******************************************************************************************************************************************************
skipping: [controller-0]
skipping: [controller-1]
skipping: [controller-2]

PLAY RECAP ***********************************************************************************************************************************************************************************************************************************
ceph-0                     : ok=0    changed=0    unreachable=0    failed=0    skipped=5    rescued=0    ignored=0   
ceph-1                     : ok=0    changed=0    unreachable=0    failed=0    skipped=5    rescued=0    ignored=0   
ceph-2                     : ok=0    changed=0    unreachable=0    failed=0    skipped=5    rescued=0    ignored=0   
compute-0                  : ok=0    changed=0    unreachable=0    failed=0    skipped=22   rescued=0    ignored=0   
compute-1                  : ok=0    changed=0    unreachable=0    failed=0    skipped=22   rescued=0    ignored=0   
controller-0               : ok=0    changed=0    unreachable=0    failed=0    skipped=44   rescued=0    ignored=0   
controller-1               : ok=0    changed=0    unreachable=0    failed=0    skipped=28   rescued=0    ignored=0   
controller-2               : ok=0    changed=0    unreachable=0    failed=0    skipped=28   rescued=0    ignored=0   
hypervisor                 : ok=2    changed=1    unreachable=0    failed=0    skipped=11   rescued=0    ignored=0   
localhost                  : ok=2    changed=2    unreachable=0    failed=0    skipped=30   rescued=0    ignored=0   
undercloud-0               : ok=27   changed=5    unreachable=0    failed=0    skipped=186  rescued=1    ignored=0   
```

**Review by mrunge — APPROVED** [review]

**Review by pleimer — APPROVED** [review]

**Comment by leifmadsen** [comment]
Also I confirm it works

**Pull request merged**
