### PR TITLE
New CRD and CSV for v1.0.3

### PR DESCRIPTION
**Pull request by csibbitt**
This is the final step to making a new STO release that support the new collectd metrics SmartGateway code.

### CODE REVIEW

**Comment by csibbitt** [comment]
I've tested this from source, but would like to retest with a full set of upstream builds.

**Comment by csibbitt** [comment]
[Produce a new SGO release that includes the new SG and bridge code](https://trello.com/c/S3EN9wur/944-produce-a-new-sgo-release-that-includes-the-new-sg-and-bridge-code)

**Comment by csibbitt** [comment]
[Fix performance problems with NEW SG code](https://trello.com/c/YqOJ9cn9/978-fix-performance-problems-with-new-sg-code)

**Comment by pleimer** [comment]
merge in master and CI will run correctly

**Comment by csibbitt** [comment]
> merge in master and CI will run correctly

@pleimer Silly question, but isn't the point of CI that we test code BEFORE merging it to master?

**Comment by pleimer** [comment]
> > merge in master and CI will run correctly
> 
> @pleimer Silly question, but isn't the point of CI that we test code BEFORE merging it to master?
Well, I had to make updates in ci.yml for it to work, so you could just copy it from master. Then, the workflow would be just what you said

**Comment by csibbitt** [comment]
> > > merge in master and CI will run correctly
> > 
> > 
> > @pleimer Silly question, but isn't the point of CI that we test code BEFORE merging it to master?
> 
> I had to make updates in ci.yml for it to work, so you could just copy it from master. Then, the workflow would be just what you said.
> 
> The positive is there is no longer a requirement to log into CRC from the script and is therefore much more future proof

Ah okay, I see. Thanks a bunch!

**Comment by csibbitt** [comment]
Fixed scorecard paths and merged w/ master for more convincing CI and scorecard test. 

```
[csibbitt@laptop service-telemetry-operator (csibbitt-944-new-sto-release) (⎈ |sto-scorecard/api-stfsg2-lab-upshift-rdu2-redhat-com:6443/kube:admin)]$ operator-sdk scorecard                                  
INFO[0000] Using config file: /home/csibbitt/cloudops/service-telemetry-operator/.osdk-scorecard.yaml 
basic:
        Spec Block Exists                  : pass
        Status Block Exists                : pass
        Writing into CRs has an effect     : pass
olm:
        Spec fields with descriptors       : pass
        Status fields with descriptors     : pass
        Provided APIs have validation      : pass
        Owned CRDs have resources listed   : pass
        CRs have at least 1 example        : pass
```

**Comment by csibbitt** [comment]
@leifmadsen told me to just merge this for now so we can accumulate changes and re-test before it hits master

**Pull request merged**
