### PR TITLE
Check for COO API before trying to delete any COO objects

### PR DESCRIPTION
**Pull request by csibbitt**

### CODE REVIEW

**Comment by csibbitt** [comment]
## Testing

### Reproduce the error

Started from a cluster with no COO and STO built from master branch. Since STO in use_redhat mode won't try to deploy prometheus & friends if COO isn't installed[1], there is no error, but there is no prometheus, either:

```
$ oc get po | grep prom
prometheus-webhook-snmp-2-build                           0/1     Completed   0             31m
```

I install the latest community Prometheus Operator[2], switch to use_community, and get the reported error:
```
$ LATEST=$(curl -s https://api.github.com/repos/prometheus-operator/prometheus-operator/releases/latest | jq -cr .tag_name)

$ curl -sL https://github.com/prometheus-operator/prometheus-operator/releases/download/${LATEST}/bundle.yaml | kubectl create -f -
[...]

$ oc edit stf
[...]
  observabilityStrategy: use_community
[...]

$ oc logs service-telemetry-operator-6585f4b846-hj82t
[...]
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Failed to find exact match for monitoring.rhobs/v1.prometheus by [kind, name, singularName, shortNames]"}
[...]
localhost                  : ok=47   changed=0    unreachable=0    failed=1    skipped=19   rescued=0    ignored=0   
```


### Try the new code

Deployed from this branch. No longer get the error, and a prometheus instance appears:
```
$ oc logs service-telemetry-operator-6585f4b846-h2gwd
[...]
localhost                  : ok=134  changed=0    unreachable=0    failed=0    skipped=61   rescued=0    ignored=0   

$ oc get po | grep prom
prometheus-default-0                                      3/3     Running     0              12m
```

Installed COO and switched to use_redhat. We get a new prometheus managed by COO and no error from STO:
```
$ oc create -f - <<EOF
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: cluster-observability-operator
  namespace: openshift-operators
spec:
  channel: development
  installPlanApproval: Automatic
  name: cluster-observability-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
EOF
subscription.operators.coreos.com/cluster-observability-operator created

$ oc edit stf
[...]
  observabilityStrategy: use_redhat
[...]

$ oc describe po prometheus-default-0 | grep Image:
    Image:         registry.redhat.io/cluster-observability-operator/coo-prometheus-config-reloader-rhel8@sha256:a7389a32a51751cb5cbf677b2c263cb148503a5628231937b3d6eda6130f6ea0
[...]

$ oc logs service-telemetry-operator-6585f4b846-h2gwd
localhost                  : ok=136  changed=0    unreachable=0    failed=0    skipped=59   rescued=0    ignored=0   
```


### Success!

We can see above that there is error-free operation in use_community mode when COO is not installed, and that we are still able to migrate from use_community to use_redhat

[1] https://github.com/infrawatch/service-telemetry-operator/blob/master/roles/servicetelemetry/tasks/main.yml#L57
[2] https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/user-guides/getting-started.md

**Comment by elfiesmelfie** [comment]
recheck

**Comment by danpawlik** [comment]
recheck

**Comment by danpawlik** [comment]
recheck

**Comment by danpawlik** [comment]
recheck

**Review by vkmc — APPROVED** [review]
Thanks for the fix and for the detailed testing Chris!

**Pull request merged**
