### PR TITLE
Add running a workload at the end of deploy

### PR DESCRIPTION
**Pull request by mrunge**
This will e.g generate metrics for ceilometer to show.

### CODE REVIEW

**Review by leifmadsen — APPROVED** [review]
Awesome!

**Comment by leifmadsen** [comment]
Feel free to merge any time, but I'm curious if you have any sort of output showing what it launches? I'd be mostly curious what projects, networks (subnets), servers, images and volumes it loads. If you don't have time to run this again I'll give it a shot later today perhaps. Thanks!

**Comment by mrunge** [comment]
In this case, it's not super satisfying. It complains at the end of its ansible run that a floating ip is not available. 
However, a workload named

`workload_instance_0` is created, an image named `workload_image_0`, a network `workload_internal_net_0`, etc.

**Comment by mrunge** [comment]
> Awesome!

Thank you for the review.

**Pull request merged**
