### PR TITLE
Use the proper parameter for SNMP timeout

### PR DESCRIPTION
**Pull request by leifmadsen**
The SNMP_TIMEOUT environment variable in the manifest_snmp_traps.j2
template for Service Telemetry Operator uses the wrong parameter,
passing port instead of timeout value to the template.

This change updates the template to use the appropriate parameter as
input.

Closes: rhbz#2213016

### CODE REVIEW

**Comment by leifmadsen** [comment]
I haven't tested this yet. I made this change based on looking at the contents when I was looking at something else to close out an issue. Oops!

**Review by csibbitt — APPROVED** [review]

**Comment by leifmadsen** [comment]
test

**Comment by leifmadsen** [comment]
I should probably do a real test here before merging to make sure I have all the proper parameters aligned and that changing the CR results in what I expect. I have that on my list for this sprint and should be able to get this merged soon. Thanks for the review!

**Comment by leifmadsen** [comment]
I was testing spin up of OCP on PSI and it resulted in a working cluster.

I deployed this branch against that cluster and performed some verification.

* deployed from index image
* checked current values for timeout in ServiceTelemetry object and in default-snmp-webhook pod. Noted value for TIMEOUT was 1
* changed ServiceTelemetry object `alerting.alertmanager.receivers.snmpTraps.timeout` from a value of `1` to `5`
* watch STO logs waiting for changes to happen, which they did
* verified default-snmp-webhook pod restarted after changes. Confirmed.
* checked default-snmp-webhook TIMEOUT value was updated to a value of `5`

This issue is verified. I will merge it now.

**Pull request merged**
