### PR TITLE
Add updated CI scripts for multi-repo coordination

### PR DESCRIPTION
**Pull request by leifmadsen**

### CODE REVIEW

**Comment by leifmadsen** [comment]
You can test this locally by having a local CRC environment with an active connection to the OpenShift environment.

```
./deploy/remove_stf.sh ; oc new-project service-telemetry ; ansible-playbook build/run-ci.yaml
```

**Comment by leifmadsen** [comment]
[Update CI shell scripts to clone and locally build images in all three repositories](https://trello.com/c/OH7zpngT/1047-update-ci-shell-scripts-to-clone-and-locally-build-images-in-all-three-repositories)

**Comment by leifmadsen** [comment]
# Deployment

```
oc get all
NAME                                                                  READY   STATUS      RESTARTS   AGE
pod/alertmanager-stf-default-0                                        2/2     Running     0          22m
pod/elastic-operator-5bfb5549ff-tll59                                 1/1     Running     0          27m
pod/elasticsearch-es-default-0                                        1/1     Running     0          22m
pod/interconnect-operator-57d9fd9574-spljg                            1/1     Running     0          27m
pod/prometheus-operator-56c9b79f8f-rnwjb                              1/1     Running     0          27m
pod/prometheus-stf-default-0                                          3/3     Running     1          22m
pod/service-telemetry-operator-1-build                                0/1     Completed   0          27m
pod/service-telemetry-operator-59b876cd78-r6dfx                       2/2     Running     0          22m
pod/smart-gateway-1-build                                             0/1     Completed   0          26m
pod/smart-gateway-operator-1-build                                    0/1     Completed   0          27m
pod/smart-gateway-operator-59cb8c44cc-rcm64                           2/2     Running     0          23m
pod/stf-default-ceilometer-notification-smartgateway-85468575drhplm   1/1     Running     0          21m
pod/stf-default-collectd-notification-smartgateway-5f67d94f54-d8xlt   1/1     Running     0          21m
pod/stf-default-collectd-telemetry-smartgateway-b65df8fdb-bwn4c       1/1     Running     0          22m
pod/stf-default-interconnect-66d98d677d-xg2sj                         1/1     Running     0          22m
pod/stf-smoketest-smoke1-qqbbr                                        1/1     Running     0          77s

NAME                                                  TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)                                AGE
service/alertmanager-operated                         ClusterIP   None            <none>        9093/TCP,9094/TCP,9094/UDP             22m
service/elasticsearch-es-default                      ClusterIP   None            <none>        <none>                                 22m
service/elasticsearch-es-http                         ClusterIP   172.30.64.22    <none>        9200/TCP                               22m
service/elasticsearch-es-transport                    ClusterIP   None            <none>        9300/TCP                               22m
service/prometheus-operated                           ClusterIP   None            <none>        9090/TCP                               22m
service/service-telemetry-operator-metrics            ClusterIP   172.30.21.176   <none>        8686/TCP,8383/TCP                      22m
service/smart-gateway-operator-metrics                ClusterIP   172.30.153.44   <none>        8686/TCP,8383/TCP                      22m
service/stf-default-collectd-telemetry-smartgateway   ClusterIP   172.30.124.55   <none>        8081/TCP                               22m
service/stf-default-interconnect                      ClusterIP   172.30.188.80   <none>        5672/TCP,8672/TCP,55671/TCP,5671/TCP   22m

NAME                                                               READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/elastic-operator                                   1/1     1            1           27m
deployment.apps/interconnect-operator                              1/1     1            1           27m
deployment.apps/prometheus-operator                                1/1     1            1           27m
deployment.apps/service-telemetry-operator                         1/1     1            1           22m
deployment.apps/smart-gateway-operator                             1/1     1            1           23m
deployment.apps/stf-default-ceilometer-notification-smartgateway   1/1     1            1           21m
deployment.apps/stf-default-collectd-notification-smartgateway     1/1     1            1           21m
deployment.apps/stf-default-collectd-telemetry-smartgateway        1/1     1            1           22m
deployment.apps/stf-default-interconnect                           1/1     1            1           22m

NAME                                                                         DESIRED   CURRENT   READY   AGE
replicaset.apps/elastic-operator-5bfb5549ff                                  1         1         1       27m
replicaset.apps/interconnect-operator-57d9fd9574                             1         1         1       27m
replicaset.apps/prometheus-operator-56c9b79f8f                               1         1         1       27m
replicaset.apps/service-telemetry-operator-59b876cd78                        1         1         1       22m
replicaset.apps/smart-gateway-operator-59cb8c44cc                            1         1         1       23m
replicaset.apps/stf-default-ceilometer-notification-smartgateway-85468575d   1         1         1       21m
replicaset.apps/stf-default-collectd-notification-smartgateway-5f67d94f54    1         1         1       21m
replicaset.apps/stf-default-collectd-telemetry-smartgateway-b65df8fdb        1         1         1       22m
replicaset.apps/stf-default-interconnect-66d98d677d                          1         1         1       22m

NAME                                        READY   AGE
statefulset.apps/alertmanager-stf-default   1/1     22m
statefulset.apps/elasticsearch-es-default   1/1     22m
statefulset.apps/prometheus-stf-default     1/1     22m

NAME                             COMPLETIONS   DURATION   AGE
job.batch/stf-smoketest-smoke1   0/1           77s        77s

NAME                                                        TYPE     FROM         LATEST
buildconfig.build.openshift.io/service-telemetry-operator   Docker   Git@master   1
buildconfig.build.openshift.io/smart-gateway                Docker   Git@master   1
buildconfig.build.openshift.io/smart-gateway-operator       Docker   Git@master   1

NAME                                                    TYPE     FROM             STATUS     STARTED          DURATION
build.build.openshift.io/service-telemetry-operator-1   Docker   Binary@d92d5f2   Complete   27 minutes ago   31s
build.build.openshift.io/smart-gateway-operator-1       Docker   Binary@2d35566   Complete   27 minutes ago   32s
build.build.openshift.io/smart-gateway-1                Docker   Binary@53c1f1d   Complete   26 minutes ago   3m23s

NAME                                                        IMAGE REPOSITORY                                                                                       TAGS     UPDATED
imagestream.image.openshift.io/service-telemetry-operator   default-route-openshift-image-registry.apps-crc.testing/service-telemetry/service-telemetry-operator   latest   27 minutes ago
imagestream.image.openshift.io/smart-gateway                default-route-openshift-image-registry.apps-crc.testing/service-telemetry/smart-gateway                latest   23 minutes ago
imagestream.image.openshift.io/smart-gateway-operator       default-route-openshift-image-registry.apps-crc.testing/service-telemetry/smart-gateway-operator       latest   26 minutes ago

NAME                                                      HOST/PORT                                                           PATH   SERVICES                   PORT    TERMINATION        WILDCARD
route.route.openshift.io/stf-default-interconnect-55671   stf-default-interconnect-55671-service-telemetry.apps-crc.testing          stf-default-interconnect   55671   passthrough/None   None
route.route.openshift.io/stf-default-interconnect-5671    stf-default-interconnect-5671-service-telemetry.apps-crc.testing           stf-default-interconnect   5671    passthrough/None   None
route.route.openshift.io/stf-default-interconnect-8672    stf-default-interconnect-8672-service-telemetry.apps-crc.testing           stf-default-interconnect   8672    edge/Redirect      None
```

# Smoketest

```
*** [SUCCESS] Smoke test job completed successfully
```

(Ya ya... trust me, it worked :) )

```
oc get jobs
NAME                   COMPLETIONS   DURATION   AGE
stf-smoketest-smoke1   1/1           89s        19m

oc logs stf-smoketest-smoke1-qqbbr
<snip>
*** [INFO] List of metric names for debugging...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0{"status":"success","data":["collectd_cpu_total","collectd_interface_if_dropped_rx_total","collectd_interface_if_dropped_tx_total","collectd_interface_if_errors_rx_total","collectd_interface_if_errors_tx_total","collectd_interface_if_octets_rx_total","collectd_interface_if_octets_tx_total","collectd_interface_if_packets_rx_total","collectd_interface_if_packets_tx_total","collectd_last_metric_for_host_status","collectd_last_pull_timestamp_seconds","collectd_metric_per_host","collectd_qpid_router_status","collectd_total_amqp_message_recv_count","collectd_total_amqp_processed_message_count","collectd_total_amqp_reconnect_count","promhttp_metric_handler_requests_in_flight","promhttp_metric_handler_requests_total","scrape_duration_seconds","scrape_sa100   816  100   816    0     0   398k      0 --:--:-- --:--:-- --:--:--  398k


*** [INFO] Checking for recent CPU metrics...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   620  100   432  100   188  72000  31333 --:--:-- --:--:-- --:--:--  121k
{"status":"success","data":{"resultType":"matrix","result":[{"metric":{"__name__":"collectd_cpu_total","cpu":"0","endpoint":"prom-http","exported_instance":"stf-smoketest-smoke1-qqbbr","service":"stf-default-collectd-telemetry-smartgateway","type":"user"},"values":[[1594094944.357,"5268815"],[1594094954.357,"5268924"],[1594094964.357,"5268991"],[1594094974.357,"5269063"],[1594094984.355,"5269154"],[1594094994.357,"5269224"]]}]}}

{"status":"success","data":{"resultType":"matrix","result":[{"metric":{"__name__":"collectd_cpu_total","cpu":"0","endpoint":"prom-http","exported_instance":"stf-smoketest-smoke1-qqbbr","service":"stf-default-collectd-telemetry-smartgateway","type":"user"},"values":[[1594094944.357,"5268815"],[1594094954.357,"5268924"],[1594094964.357,"5268991"],[1594094974.357,"5269063"],[1594094984.355,"5269154"],[1594094994.357,"5269224"]]}]}}
*** [INFO] Get documents for this test from ElasticSearch...
*** [INFO] Found 60 documents


*** [INFO] Testing completed with success


```

**Comment by csibbitt** [comment]
Amazing. I haven't tested it myself but I like the way it reads and I did check the CI output, which is pretty convincing. This is so useful!

**Comment by leifmadsen** [comment]
> Amazing. I haven't tested it myself but I like the way it reads and I did check the CI output, which is pretty convincing. This is so useful!

After lunch I think I'm going to try this against @paramite work locally in my CRC to see if it passes before asking him to merge it into his branch.

Once I have validation it works on another set of branches with sync'd names, I'll be more confident replacing our existing CI scripts with this.

**Comment by pleimer** [comment]
> > Amazing. I haven't tested it myself but I like the way it reads and I did check the CI output, which is pretty convincing. This is so useful!
> 
> After lunch I think I'm going to try this against @paramite work locally in my CRC to see if it passes before asking him to merge it into his branch.
> 
> Once I have validation it works on another set of branches with sync'd names, I'll be more confident replacing our existing CI scripts with this.

**Comment by leifmadsen** [comment]
Found a bug with how builds operate. They are not being pulled from the local directory, so I'm working on adjusting things to validate that happens.

**Comment by leifmadsen** [comment]
I've re-run this locally in this branch, and I also merged it into @paramite working branch(es) for Ceilometer metrics work, and it works there as well. I also made sure to validate that the service-telemetry-operator build when modified locally results in the changes showing up in the local image.

**Pull request merged**
