### PR TITLE
[Jenkins] Remove jenkins config and deployment files

### PR DESCRIPTION
**Pull request by elfiesmelfie**
We are now using Zuul to replace Jenkins

Depends-On: https://github.com/openstack-k8s-operators/ci-framework/pull/1403

### CODE REVIEW

**Comment by elfiesmelfie** [comment]
recheck

**Review by leifmadsen — APPROVED** [review]

**Review by csibbitt — APPROVED** [review]

**Comment by elfiesmelfie** [comment]
recheck

**Comment by elfiesmelfie** [comment]
recheck

**Comment by elfiesmelfie** [comment]
recheck

**Comment by leifmadsen** [comment]
I mean... _not_ seeing stf-crc-ocp_413-... jobs kinda indicates this worked right? :)

**Comment by elfiesmelfie** [comment]
You're thinking of the PR that removed zuul ocp 4.13 jobs.

This is removing jenkins.

**Comment by elfiesmelfie** [comment]
recheck

**Comment by elfiesmelfie** [comment]
recheck

**Pull request merged**
