### PR TITLE
Add baseImage parameter to Grafana parameter

### PR DESCRIPTION
**Pull request by leifmadsen**
Add the baseImage parameter to the graphing.grafana spec parameters of
the ServiceTelemetry object. Defaults to docker.io/grafana/grafana:8.1.2
but can be overridden at deployment time.

Resolves: rhbz#1998551

### CODE REVIEW

**Review by pleimer — APPROVED** [review]
not tested but looks good to me

**Comment by leifmadsen** [comment]
Currently blocked on some other work, but will get back to this hopefully today and provide a test report.

**Comment by leifmadsen** [comment]
recheck

**Comment by leifmadsen** [comment]
Just doing some final testing on this and making sure the values populate and display the way I want in the UI. Will then double check that it actually works :)

**Comment by leifmadsen** [comment]
Looks good. Just need to verify everything and this is ready.
image

**Comment by leifmadsen** [comment]
Verified to work. Was going to hack on stf-run-ci as well in this patch to get Grafana Operator and Grafana set up, but that feels like an overreach for what I'm doing here. Will definitely circle back soon and add Grafana Operator to the testing system though.

**Pull request merged**
