### PR TITLE
Set correct k8s collection pin and force new image pull

### PR DESCRIPTION
**Pull request by csibbitt**

### CODE REVIEW

**Review by leifmadsen — APPROVED** [review]
Looks sane to me

**Comment by csibbitt** [comment]
Trying to test this led to me breaking our new CI server where this seemed to be required, so I'll hold off on merging it until we sort that out and can test this actually works.

**Comment by csibbitt** [comment]
https://github.com/infrawatch/service-telemetry-operator/pull/374 fixes the CI server, and this verified okay after that. You can see the results (on the continuous-integration/jenkins/pr-merge test) here: https://github.com/infrawatch/service-telemetry-operator/pull/371

**Comment by csibbitt** [comment]
test

**Pull request merged**
