### PR TITLE
Update oc to 4.11 in jenkins agent

### PR DESCRIPTION
**Pull request by csibbitt**
Got this during CI:
```
+ OCP_PROJECT=pr-388-4
+ ./tests/smoketest/smoketest.sh
*** Please install 'oc' client version 4.10 or later ***
```

Let's see...
```
$ oc run -it testagent --image=image-registry.openshift-image-registry.svc:5000/ci/jenkins-agent --command -- /bin/sh
If you don't see a command prompt, try pressing enter.
sh-4.4# oc version
Client Version: v4.2.0-alpha.0-1560-g142cb44
```

Woah, yikes. 4.2??

Patch the Dockerfile...
```
$ oc start-build jenkins-agent --from-file ./Dockerfile --follow=true
[...]
$ oc run -it testagent --image=image-registry.openshift-image-registry.svc:5000/ci/jenkins-agent --command -- /bin/sh
If you don't see a command prompt, try pressing enter.
sh-4.4# oc version
Client Version: 4.10.41
```

### CODE REVIEW

**Comment by csibbitt** [comment]
test

**Review by leifmadsen — APPROVED** [review]

**Comment by csibbitt** [comment]
test

**Comment by csibbitt** [comment]
test

**Comment by csibbitt** [comment]
test

**Comment by leifmadsen** [comment]
test

**Comment by leifmadsen** [comment]
test

**Comment by csibbitt** [comment]
test

**Comment by csibbitt** [comment]
test

**Comment by csibbitt** [comment]
test

**Comment by csibbitt** [comment]
test

**Comment by csibbitt** [comment]
test

**Pull request merged**
