### PR TITLE
Limit port 5672 to localhost

### PR DESCRIPTION
**Pull request by csibbitt**
This port is listening with no TLS or authentication so should be restricted to local access for qdstat

### CODE REVIEW

**Comment by csibbitt** [comment]
## Testing

Initially wanted to remove this listener entirely, but found that we'd tried and backpedaled on that once before: https://github.com/infrawatch/service-telemetry-operator/commit/5f380f5d0fbd0d944dae67844388ab3118413a50

Sure enough, if I remove the port entirely I see this:
```
$ oc exec -it deploy/default-interconnect -- qdstat --connections

ConnectionException: Connection amqp://0.0.0.0:amqp disconnected: Condition('proton.pythonio', 'Connection refused to all addresses')
command terminated with exit code 1
```

So instead I just restricted the port to 127.0.0.1

### Before the change

Port 5672 is found in nmap

```
$ kubectl get pods -o json | jq -r '.items[] | "\(.metadata.name): \(.status.podIP)"' | grep default-interconnect
default-interconnect-fb96557cc-zz565: 10.128.0.220

$ oc run --privileged=true --image=quay.io/instrumentisto/nmap --rm -i -t nm -- -Pn -p- 10.128.0.220
[...]
Host is up (0.0000080s latency).
Not shown: 65527 closed tcp ports (reset)
PORT      STATE    SERVICE
5671/tcp  open     amqps
5672/tcp  open     amqp
5673/tcp  open     jms
8672/tcp  open     unknown
8888/tcp  open     sun-answerbook
22623/tcp filtered unknown
22624/tcp filtered unknown
55671/tcp open     unknown
MAC Address: 0A:58:0A:80:00:DC (Unknown)
```

### After the change

Port 5672 is NOT found in nmap, but qdstat commands still work

```
$ kubectl get pods -o json | jq -r '.items[] | "\(.metadata.name): \(.status.podIP)"' | grep default-interconnect
default-interconnect-77664697fd-fhpfx: 10.130.0.217

$ oc run --privileged=true --image=quay.io/instrumentisto/nmap --rm -i -t nm -- -Pn -p- 10.130.0.217
[...]
Host is up (0.00024s latency).
Not shown: 65528 closed tcp ports (reset)
PORT      STATE    SERVICE
5671/tcp  open     amqps
5673/tcp  open     jms
8672/tcp  open     unknown
8888/tcp  open     sun-answerbook
22623/tcp filtered unknown
22624/tcp filtered unknown
55671/tcp open     unknown
MAC Address: 0A:58:0A:82:00:D9 (Unknown)

$ oc exec -it deploy/default-interconnect -- qdstat --connections
2024-05-13 18:31:12.415775 UTC
default-interconnect-77664697fd-fhpfx

Connections
  id  host             container                             role    dir  security     authentication  tenant  last dlv      uptime
  =========================================================================================================================================
  1   127.0.0.1:35118  84bc110a-2732-4c73-9eea-e2653c1c7cea  normal  in   no-security  no-auth                 000:00:00:00  000:00:00:00
```

**Comment by csibbitt** [comment]
recheck

**Comment by csibbitt** [comment]
recheck

**Review by vkmc — APPROVED** [review]
LGTM, thanks Chris!

**Review by elfiesmelfie — APPROVED** [review]

**Comment by vkmc** [comment]
recheck

**Comment by vkmc** [comment]
recheck

**Comment by csibbitt** [comment]
recheck

**Comment by vkmc** [comment]
recheck

**Pull request merged**
