### PR TITLE
[ansible-lint] Use fqcn for modules

### PR DESCRIPTION
**Pull request by elfiesmelfie**

### CODE REVIEW

**Comment by leifmadsen** [comment]
Are these changes because CI Framework is using an Ansible version newer than 2.9? I see that we have GHA with some ansible linting, but it's covering the `roles/servicetelemetry/` directory specifically, with things targeting Ansible 2.9 (since the base operator image is still using Ansible 2.9).

Should there be another GHA lint test added with this to make sure we're in alignment with the system that wanted the expanded name change?

**Comment by elfiesmelfie** [comment]
> Are these changes because CI Framework is using an Ansible version newer than 2.9? I see that we have GHA with some ansible linting, but it's covering the `roles/servicetelemetry/` directory specifically, with things targeting Ansible 2.9 (since the base operator image is still using Ansible 2.9).
> 
> Should there be another GHA lint test added with this to make sure we're in alignment with the system that wanted the expanded name change?

I'm not completely sure how this came along. I think it came up because of a change in the k8s collection, since it was renamed.

This is addressing a small set of the ansible-lint issues. We could update a check in GHA to cover this as well.
An additional change for better logging will include adding task names to make it easier to see what's going on of you're watching the logstream or perusing the logs to debug

**Review by leifmadsen — COMMENTED** [review]
OK thanks for the info. I'm more interested in landing these changes for CI than to expand scope to add more CI for linting, so I'm happy to see this land :)

**Review by leifmadsen — APPROVED** [review]

**Comment by leifmadsen** [comment]
So I did a local test, and everything is fine. However, do we have a target version of Ansible we should be validating this works with?

FWIW I tested with Ansible 2.14 on my Fedora 38 desktop. I'm not sure if we need to validate this works with Ansible 2.9?

**Comment by leifmadsen** [comment]
test

**Comment by leifmadsen** [comment]
I went to resolve conflicts, but realized some code i moved around causes a conflict here because I was using the short form of the module name. Will resolve tomorrow. The `pre-clean.yml` changes I landed today just need to be adjusted by rebasing here and updating that moved code block.

**Review by vkmc — APPROVED** [review]
LGTM

**Comment by vkmc** [comment]
Tried to submit a rebase with the master branch, fix the linting issues that Leif mentioned, but it didn't go as expected. Let's sync to fix those.

One question I also wanted to make is, I assume the linting fixes are targeted to stf-run-ci. Otherwise, I saw some other parts of the repo that needs fixing.

**Comment by leifmadsen** [comment]
I'm starting on a conflict resolve now and will post changes shortly.

**Comment by leifmadsen** [comment]
> I'm starting on a conflict resolve now and will post changes shortly.

Never mind, Emma fixed it 45 mins ago :)

**Comment by leifmadsen** [comment]
test

**Comment by elfiesmelfie** [comment]
I'm going to re-test this, since the failure in jenkins was fixed in PR#464

**Pull request merged**
