### PR TITLE
[master merged] Add snmp traps container and config

### PR DESCRIPTION
**Pull request by leifmadsen**
STF refactoring merged in to working branch mrunge-snmptraps-revised. I think this is the ideal direction for commit tracking purposes? (Messy log, but that seems to be our style.)

### CODE REVIEW

**Comment by leifmadsen** [comment]
I did not make any attempt to migrate the original code to the new syntax/format other than to place it "as-is" from the original source. I expect more commits to this branch, such as running `operator-sdk generate bundle` and other commands to bring it in line with STF 1.1 base.

**Comment by leifmadsen** [comment]
Just merged master back in to this branch to get it caught up with STF 1.1 release work. I will continue to update this via commits to align the parameters to the new CRD model.

**Comment by leifmadsen** [comment]
Quick set of tests:

```
oc get secret alertmanager-default -oyaml
apiVersion: v1
data:
  alertmanager.yaml: Z2xvYmFsOgogIHJlc29sdmVfdGltZW91dDogNW0Kcm91dGU6CiAgZ3JvdXBfYnk6IFsnam9iJ10KICBncm91cF93YWl0OiAzMHMKICBncm91cF9pbnRlcnZhbDogNW0KICByZXBlYXRfaW50ZXJ2YWw6IDEyaAogIHJlY2VpdmVyOiAnc25tcF93aCcKcmVjZWl2ZXJzOgotIG5hbWU6ICdzbm1wX3doJwogIHdlYmhvb2tfY29uZmlnczoKICAgICAtIHVybDogJ2h0dHA6Ly9kZWZhdWx0LXByb21ldGhldXMtd2ViaG9vay1zbm1wOjkwOTkn
kind: Secret
metadata:
  creationTimestamp: "2020-10-26T17:07:34Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:alertmanager.yaml: {}
      f:metadata:
        f:ownerReferences:
          .: {}
          k:{"uid":"967eaf14-a9ce-43c0-96fa-280462bfb5e4"}:
            .: {}
            f:apiVersion: {}
            f:kind: {}
            f:name: {}
            f:uid: {}
      f:type: {}
    manager: Swagger-Codegen
    operation: Update
    time: "2020-10-29T03:30:51Z"
  name: alertmanager-default
  namespace: service-telemetry
  ownerReferences:
  - apiVersion: infra.watch/v1beta1
    kind: ServiceTelemetry
    name: default
    uid: 967eaf14-a9ce-43c0-96fa-280462bfb5e4
  resourceVersion: "2247803"
  selfLink: /api/v1/namespaces/service-telemetry/secrets/alertmanager-default
  uid: 85503c8b-8dfa-4e18-b813-a412322728db
type: Opaque
```

```
 echo "Z2xvYmFsOgogIHJlc29sdmVfdGltZW91dDogNW0Kcm91dGU6CiAgZ3JvdXBfYnk6IFsnam9iJ10KICBncm91cF93YWl0OiAzMHMKICBncm91cF9pbnRlcnZhbDogNW0KICByZXBlYXRfaW50ZXJ2YWw6IDEyaAogIHJlY2VpdmVyOiAnc25tcF93aCcKcmVjZWl2ZXJzOgotIG5hbWU6ICdzbm1wX3doJwogIHdlYmhvb2tfY29uZmlnczoKICAgICAtIHVybDogJ2h0dHA6Ly9kZWZhdWx0LXByb21ldGhldXMtd2ViaG9vay1zbm1wOjkwOTkn" | base64 -d
global:
  resolve_timeout: 5m
route:
  group_by: ['job']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 12h
  receiver: 'snmp_wh'
receivers:
- name: 'snmp_wh'
  webhook_configs:
     - url: 'http://default-prometheus-webhook-snmp:9099'
```

```
 oc get services
NAME                                     TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)                                         AGE
alertmanager-operated                    ClusterIP   None             <none>        9093/TCP,9094/TCP,9094/UDP                      2d7h
default-cloud1-ceil-meter-smartgateway   ClusterIP   172.30.22.142    <none>        8081/TCP                                        2d10h
default-cloud1-coll-meter-smartgateway   ClusterIP   172.30.8.104     <none>        8081/TCP                                        2d10h
default-interconnect                     ClusterIP   172.30.101.192   <none>        5672/TCP,8672/TCP,55671/TCP,5671/TCP,5673/TCP   2d10h
default-prometheus-webhook-snmp          ClusterIP   172.30.219.41    <none>        9099/TCP                                        3m16s
elasticsearch-es-default                 ClusterIP   None             <none>        9200/TCP                                        2d7h
elasticsearch-es-http                    ClusterIP   172.30.40.54     <none>        9200/TCP                                        2d7h
elasticsearch-es-transport               ClusterIP   None             <none>        9300/TCP                                        2d7h
grafana-operator-metrics                 ClusterIP   172.30.1.18      <none>        8080/TCP                                        2d6h
grafana-service                          ClusterIP   172.30.66.205    <none>        3000/TCP                                        2d6h
ibm-auditlogging-operator-metrics        ClusterIP   172.30.125.219   <none>        8383/TCP,8686/TCP                               2d6h
prometheus-operated                      ClusterIP   None             <none>        9090/TCP                                        2d7h
service-telemetry-operator-metrics       ClusterIP   172.30.254.126   <none>        8383/TCP,8686/TCP                               2d13h
smart-gateway-operator-metrics           ClusterIP   172.30.167.210   <none>        8383/TCP,8686/TCP                               2d14h
```

```
oc get pods
NAME                                                      READY   STATUS    RESTARTS   AGE
alertmanager-default-0                                    2/2     Running   0          2d7h
default-cloud1-ceil-event-smartgateway-6cfb65478c-g5q82   1/1     Running   0          2d
default-cloud1-ceil-meter-smartgateway-58f885c76d-xmxwn   1/1     Running   0          2d
default-cloud1-coll-event-smartgateway-58fbbd4485-rl9bd   1/1     Running   0          2d
default-cloud1-coll-meter-smartgateway-7c6fc495c4-jn728   2/2     Running   0          2d
default-interconnect-79d9994b5-xnfvv                      1/1     Running   0          2d10h
default-snmp-webhook-f8fb9fb5c-s6w9g                      1/1     Running   0          5m35s
elastic-operator-746f86c956-jkvcq                         1/1     Running   0          2d14h
elasticsearch-es-default-0                                1/1     Running   0          2d7h
grafana-deployment-6f9f5f8cbd-rnt7x                       1/1     Running   0          2d6h
grafana-operator-788b69d9b8-jj6nj                         1/1     Running   0          2d6h
ibm-auditlogging-operator-bb9876dc6-6bfn8                 1/1     Running   0          2d6h
interconnect-operator-5b474bdddc-sztsj                    1/1     Running   0          2d14h
prometheus-default-0                                      3/3     Running   1          2d7h
prometheus-operator-7dfb478c8b-bfd4j                      1/1     Running   0          2d14h
service-telemetry-operator-6c6cd47cb6-pb8p8               2/2     Running   0          11m
smart-gateway-operator-7f49676d5d-nqzmp                   2/2     Running   0          2d14h
```

**Comment by leifmadsen** [comment]
Note to self, tomorrow check about loading the container image to load from environment variable defined in the `operator.yaml` when creating the Operator. We shouldn't be hard coding access to images in the Ansible role itself.

**Review by mrunge — APPROVED** [review]
Thank you, this looks good to me.

**Comment by leifmadsen** [comment]
Going to merge this down. We can find any issues during testing. Thanks!

**Pull request merged**
