### PR TITLE
Break out common configuration to enable-stf.yaml

### PR DESCRIPTION
**Pull request by leifmadsen**
* Make controller and compute resources configurable
* Align to documentation

### CODE REVIEW

**Comment by leifmadsen** [comment]
I am working on aligning this to the new documentation changes in stable-1.3 for both OSP13 and 16. Will do manual testing.

**Comment by leifmadsen** [comment]
**OSP16.1 Testing**

```bash
PLAY RECAP ***********************************************************************************************************************************************************************************************************************************
ceph-0                     : ok=0    changed=0    unreachable=0    failed=0    skipped=5    rescued=0    ignored=0   
ceph-1                     : ok=0    changed=0    unreachable=0    failed=0    skipped=5    rescued=0    ignored=0   
ceph-2                     : ok=0    changed=0    unreachable=0    failed=0    skipped=5    rescued=0    ignored=0   
compute-0                  : ok=0    changed=0    unreachable=0    failed=0    skipped=22   rescued=0    ignored=0   
compute-1                  : ok=0    changed=0    unreachable=0    failed=0    skipped=22   rescued=0    ignored=0   
controller-0               : ok=0    changed=0    unreachable=0    failed=0    skipped=44   rescued=0    ignored=0   
controller-1               : ok=0    changed=0    unreachable=0    failed=0    skipped=28   rescued=0    ignored=0   
controller-2               : ok=0    changed=0    unreachable=0    failed=0    skipped=28   rescued=0    ignored=0   
hypervisor                 : ok=2    changed=1    unreachable=0    failed=0    skipped=11   rescued=0    ignored=0   
localhost                  : ok=2    changed=2    unreachable=0    failed=0    skipped=30   rescued=0    ignored=0   
undercloud-0               : ok=29   changed=5    unreachable=0    failed=0    skipped=196  rescued=1    ignored=0   

-- deployment completed
>> Cloud name: cloudops04
>> Overcloud domain: osp-cloudops-04
>> STF enabled: true
>> Gnocchi enabled: true
>> OSP version: 16.1
>> OSP build: passed_phase2
>> OSP topology: undercloud:1,controller:3,compute:2,ceph:3

real	124m13.988s
user	11m30.788s
sys	1m52.521s
```

```yaml
[stack@undercloud-0 ~]$ cat virt/enable-stf.yaml 
parameter_defaults:
    CeilometerQdrPublishMetrics: true
    CollectdAmqpInterval: 5
    CollectdConnectionType: amqp1
    CollectdDefaultPollingInterval: 5
    CollectdEnableLibpodstats: true
    CollectdEnableSensubility: true
    CollectdExtraPlugins:
    - vmem
    CollectdSensubilityTransport: amqp1
    EventPipelinePublishers: []
    ExtraConfig:
        ceilometer::agent::polling::polling_interval: 30
        ceilometer::agent::polling::polling_meters:
        - cpu
        - disk.*
        - ip.*
        - image.*
        - memory
        - memory.*
        - network.*
        - perf.*
        - port
        - port.*
        - switch
        - switch.*
        - storage.*
        - volume.*
        collectd::plugin::amqp1::send_queue_limit: 50
        collectd::plugin::memcached::instances:
            local:
                host: '%{hiera(fqdn_canonical)}'
                port: 11211
        collectd::plugin::virt::hostname_format: name uuid hostname
        collectd::plugin::virt::plugin_instance_format: metadata
        collectd::plugin::vmem::verbose: true
    ManagePipeline: true
    ManagePolling: true
    PipelinePublishers: []
```

```yaml
[stack@undercloud-0 ~]$ cat virt/gnocchi-connectors.yaml 
parameter_defaults:
    CeilometerEnableGnocchi: true
    CeilometerEnablePanko: false
    EventPipelinePublishers:
    - gnocchi://?filter_project=service
    GnocchiArchivePolicy: high
    GnocchiBackend: rbd
    GnocchiRbdPoolName: metrics
    PipelinePublishers:
    - gnocchi://?filter_project=service
resource_registry:
    OS::TripleO::Services::AodhApi: /usr/share/openstack-tripleo-heat-templates/deployment/aodh/aodh-api-container-puppet.yaml
    OS::TripleO::Services::AodhEvaluator: /usr/share/openstack-tripleo-heat-templates/deployment/aodh/aodh-evaluator-container-puppet.yaml
    OS::TripleO::Services::AodhListener: /usr/share/openstack-tripleo-heat-templates/deployment/aodh/aodh-listener-container-puppet.yaml
    OS::TripleO::Services::AodhNotifier: /usr/share/openstack-tripleo-heat-templates/deployment/aodh/aodh-notifier-container-puppet.yaml
    OS::TripleO::Services::GnocchiApi: /usr/share/openstack-tripleo-heat-templates/deployment/gnocchi/gnocchi-api-container-puppet.yaml
    OS::TripleO::Services::GnocchiMetricd: /usr/share/openstack-tripleo-heat-templates/deployment/gnocchi/gnocchi-metricd-container-puppet.yaml
    OS::TripleO::Services::GnocchiStatsd: /usr/share/openstack-tripleo-heat-templates/deployment/gnocchi/gnocchi-statsd-container-puppet.yaml
```

```yaml
[stack@undercloud-0 ~]$ cat virt/stf-connectors.yaml 
parameter_defaults:
    CeilometerQdrEventsConfig:
        driver: amqp
        topic: cloudops04-event
    CeilometerQdrMetricsConfig:
        driver: amqp
        topic: cloudops04-metering
    CephStorageExtraConfig:
        tripleo::profile::base::metrics::collectd::amqp_host: '%{hiera(''storage'')}'
        tripleo::profile::base::metrics::qdr::listener_addr: '%{hiera(''storage'')}'
    CollectdAmqpInstances:
        cloudops04-notify:
            format: JSON
            notify: true
            presettle: false
        cloudops04-telemetry:
            format: JSON
            presettle: false
    CollectdSensubilityLogLevel: DEBUG
    CollectdSensubilityResultsChannel: collectd/cloudops04-notify
    ExtraConfig:
        collectd::plugin::ceph::daemons:
        - ceph-osd.0
        - ceph-osd.1
        - ceph-osd.2
        - ceph-osd.3
        - ceph-osd.4
        - ceph-osd.5
        - ceph-osd.6
        - ceph-osd.7
        - ceph-osd.8
        - ceph-osd.9
        - ceph-osd.10
        - ceph-osd.11
        - ceph-osd.12
        - ceph-osd.13
        - ceph-osd.14
    MetricsQdrConnectors:
    -   host: default-interconnect-5671-service-telemetry.apps.stf.<SNIP>
        port: 443
        role: edge
        sslProfile: sslProfile
        verifyHostname: false
    MetricsQdrSSLProfiles:
    -   name: sslProfile
```

**Comment by leifmadsen** [comment]
OSP13 deployment seems to work. Have to test one additional change (and fix up our docs for STF 1.3) to account for the different `CollectdDefaultPlugins` list.

```
PLAY RECAP ***********************************************************************************************************************************************************************************************************************************
ceph-0                     : ok=0    changed=0    unreachable=0    failed=0    skipped=113  rescued=0    ignored=0   
ceph-1                     : ok=0    changed=0    unreachable=0    failed=0    skipped=113  rescued=0    ignored=0   
ceph-2                     : ok=0    changed=0    unreachable=0    failed=0    skipped=113  rescued=0    ignored=0   
compute-0                  : ok=0    changed=0    unreachable=0    failed=0    skipped=113  rescued=0    ignored=0   
compute-1                  : ok=0    changed=0    unreachable=0    failed=0    skipped=113  rescued=0    ignored=0   
controller-0               : ok=0    changed=0    unreachable=0    failed=0    skipped=113  rescued=0    ignored=0   
controller-1               : ok=0    changed=0    unreachable=0    failed=0    skipped=113  rescued=0    ignored=0   
controller-2               : ok=0    changed=0    unreachable=0    failed=0    skipped=113  rescued=0    ignored=0   
hypervisor                 : ok=2    changed=0    unreachable=0    failed=0    skipped=4    rescued=0    ignored=0   
localhost                  : ok=26   changed=4    unreachable=0    failed=0    skipped=31   rescued=0    ignored=0   
undercloud-0               : ok=318  changed=120  unreachable=0    failed=0    skipped=934  rescued=0    ignored=2   

-- deployment completed
>> Cloud name: cloudops06
>> Overcloud domain: osp-cloudops-06
>> STF enabled: true
>> OSP version: 13
>> OSP build: 7.9-passed_phase2
>> OSP topology: undercloud:1,controller:3,compute:2,ceph:3

real	153m13.666s
user	11m55.958s
sys	2m8.812s
```

```yaml
[stack@undercloud-0 ~]$ cat virt/enable-stf.yaml 
parameter_defaults:
    CeilometerQdrPublishEvents: true
    CeilometerQdrPublishMetrics: true
    CollectdAmqpInterval: 5
    CollectdConnectionType: amqp1
    CollectdDefaultPollingInterval: 5
    CollectdDefaultPlugins:
    - cpu
    - df
    - disk
    - hugepages
    - interface
    - load
    - memory
    - processes
    - unixsock
    - uptime

    CollectdExtraPlugins:
    - vmem
    EventPipelinePublishers: []
    ExtraConfig:
        ceilometer::agent::polling::polling_interval: 30
        ceilometer::agent::polling::polling_meters:
        - cpu
        - disk.*
        - ip.*
        - image.*
        - memory
        - memory.*
        - network.*
        - perf.*
        - port
        - port.*
        - switch
        - switch.*
        - storage.*
        - volume.*
        collectd::plugin::amqp1::send_queue_limit: 50
        collectd::plugin::virt::plugin_instance_format: metadata
        collectd::plugin::vmem::verbose: true
    ManagePipeline: true
    ManagePolling: true
    PipelinePublishers: []
```

```yaml
[stack@undercloud-0 ~]$ cat virt/stf-connectors.yaml 
parameter_defaults:
    CeilometerQdrEventsConfig:
        driver: amqp
        topic: cloudops06-event
    CeilometerQdrMetricsConfig:
        driver: amqp
        topic: cloudops06-metering
    CollectdAmqpInstances:
        cloudops06-notify:
            format: JSON
            notify: true
            presettle: false
        cloudops06-telemetry:
            format: JSON
            presettle: false
    MetricsQdrConnectors:
    -   host: default-interconnect-5671-service-telemetry.apps.stf.<SNIP>
        port: 443
        role: edge
        sslProfile: sslProfile
        verifyHostname: false
    MetricsQdrSSLProfiles:
    -   caCertFileContent: '-----BEGIN CERTIFICATE-----
            <snip>

            -----END CERTIFICATE-----

            '
        name: sslProfile
```

**Comment by leifmadsen** [comment]
Some additional changes will need to be evaluated to make sure the data is configured the same. For example, enabling the `cpu` plugin on collectd for OSP13 doesn't result in the same metrics since it looks like the plugin is not set to send CPU stats as percentage like OSP16.

Will follow up on additional configuration options as these will need to be documented first, then ported in to the testing framework.

**Review by csibbitt — APPROVED** [review]

**Review by mrunge — APPROVED** [review]
Can't spot anything obviously wrong here.

**Comment by leifmadsen** [comment]
Thanks!

**Pull request merged**
