### PR TITLE
Add a Zuul job for nightly bundles and index deploy

### PR DESCRIPTION
**Pull request by vkmc**
Adds a Zuul job definition to test the creation of an index image using pre build nightly bundles on OCP 4.14

Depends-On: https://github.com/infrawatch/service-telemetry-operator/pull/597

### CODE REVIEW

**Comment by vkmc** [comment]
recheck

**Comment by vkmc** [comment]
recheck

**Comment by vkmc** [comment]
recheck

**Comment by vkmc** [comment]
recheck

**Comment by vkmc** [comment]
recheck

**Review by elfiesmelfie — APPROVED** [review]

**Comment by vkmc** [comment]
recheck

**Comment by vkmc** [comment]
recheck

**Pull request merged**
