### PR TITLE
Adjust Alertmanager SAR to be more specific

### PR DESCRIPTION
**Pull request by csibbitt**
* This matches recent changes in prometheus[1] and grafana[2]
* Also adds the required permission for prometheus-stf to query smart gateways

[1] https://github.com/infrawatch/service-telemetry-operator/pull/549/files#diff-2cf84bcf66f12393c86949ec0d3f16c473a650173d55549bb02556d23aa22bd2R46
[2] https://github.com/infrawatch/service-telemetry-operator/pull/550/files#diff-ae71801975adb4f8dd4aa5479a66ad46e46f17de40f9d147b2e09e13ce26633eR45

Depends-on: https://github.com/infrawatch/smart-gateway-operator/pull/154
Depends-on: https://github.com/infrawatch/service-telemetry-operator/pull/549

### CODE REVIEW

**Comment by csibbitt** [comment]
All of the rdo test failures were due to a problem building prometheus-webhook-snmp

**Comment by csibbitt** [comment]
recheck

**Comment by csibbitt** [comment]
recheck

**Comment by csibbitt** [comment]
recheck

**Comment by csibbitt** [comment]
New errors, this time trying to set up the index for index based deployments. This wasn't happening earlier, and is not related to my change. 

```
2023-12-13 18:35:05.557973 | TASK [../build/stf-run-ci : Set the operator_registry_image]
2023-12-13 18:35:05.610908 | controller | ok
2023-12-13 18:35:05.620204 | 
2023-12-13 18:35:05.620363 | TASK [../build/stf-run-ci : Try to get the image info for the operator registry image]
2023-12-13 13:35:06.604574 | controller | error: unable to read image registry.redhat.io/openshift4/ose-operator-registry:v4.13: Head "https://registry.redhat.io/v2/openshift4/ose-operator-registry/manifests/v4.13": unauthorized: Please login to the Red Hat Registry using your Customer Portal credentials. Further instructions can be found here: https://access.redhat.com/RegistryAuthentication
2023-12-13 18:35:06.654455 | controller | ERROR
2023-12-13 18:35:06.654636 | controller | {
2023-12-13 18:35:06.654686 | controller |   "delta": "0:00:00.376040",
2023-12-13 18:35:06.654719 | controller |   "end": "2023-12-13 13:35:06.610973",
2023-12-13 18:35:06.654747 | controller |   "msg": "non-zero return code",
2023-12-13 18:35:06.654774 | controller |   "rc": 1,
2023-12-13 18:35:06.654800 | controller |   "start": "2023-12-13 13:35:06.234933"
2023-12-13 18:35:06.654829 | controller | }
2023-12-13 18:35:06.654870 | controller | ERROR: Ignoring Errors
```

A bit worried that this one won't clear on a retry, but willing to give it one more shot.

**Comment by csibbitt** [comment]
recheck

**Review by leifmadsen — APPROVED** [review]

**Comment by csibbitt** [comment]
stf-crc-ocp_413-local_build  has failed 4/4 times, and in 3 different ways! None of them related to my change AFAICT (they fail before the point where that process diverges from stf-crc-ocp_413-local_build-index_deploy, which passed all 4 times)

I'm going to try again, but I'd like zuul to know that I'm getting impatient! ;)

**Comment by csibbitt** [comment]
recheck

**Pull request merged**
