### PR TITLE
QDR Auth for infrared 17.1 script

### PR DESCRIPTION
**Pull request by csibbitt**

### CODE REVIEW

**Comment by leifmadsen** [comment]
Doing a local test here since I needed to re-hook up a cluster to my STF. Using this command:

```bash
OCP_ROUTE_IP="10.0.111.41" CA_CERT_FILE_CONTENT="$(oc get secret/default-interconnect-selfsigned -o jsonpath='{.data.ca\.crt}' | base64 -d)" AMQP_HOST="$(oc get route default-interconnect-5671 -ojsonpath='{.spec.host}')" AMQP_PASS="$(oc get secret default-interconnect-users -o json | jq -r .data.guest | base64 -d)" ENABLE_STF_CONNECTORS=true ENABLE_GNOCCHI_CONNECTORS=false CONTROLLER_MEMORY="24000" COMPUTE_CPU="6" COMPUTE_MEMORY="24000" LIBVIRT_DISKPOOL="/home/libvirt/images" ./infrared-openstack.sh
```

**Comment by leifmadsen** [comment]
I ended up accidentally deploying the script before switching my STF deployment to `auth: basic`. I did it right away, but obviously the password wouldn't be generated by that point. The result is a successful deployment, but with this configuration on the OSP side:

```yaml
connector {
    host: default-interconnect-5671-service-telemetry.apps.stf15comm.rhos-d.infra.prod.upshift.rdu2.redhat.com
    port: 443
    role: edge
    saslPassword: pass:<<AMQP_PASS>>
    saslUsername: guest@default-interconnect
    sslProfile: sslProfile
    verifyHostname: false
}
```

I would suggest adding a small verification step in the script that will check for an empty result. My instinct is if no password is provided to have the script generate the configuration as if `auth: none` is setup, and if a non-empty value is returned, then to generate the template for the <<AUTH_PASS>> part?

Alternatively throw out a warning and `exit 1`.

**Comment by csibbitt** [comment]
@leifmadsen Thanks for the test.

A warning IS produced if you have not password set: https://github.com/infrawatch/service-telemetry-operator/pull/517/files#diff-3b27a19d8b23e2fb26919a3b041598846c0b5cca89f25de1af59e50444460467R169

What explains your experience is that the password IS generated by the Interconnect Operator, even if you don't set `auth: basic` in the STF object (this secret has been in our system the whole time, we just always ignored it)

I believe the bug you found is a failure to add <<AMQP_PASS>> to the sed substitutions here: https://github.com/infrawatch/service-telemetry-operator/pull/517/files#diff-3b27a19d8b23e2fb26919a3b041598846c0b5cca89f25de1af59e50444460467R99

I'll put up a fix, thanks!

**Comment by leifmadsen** [comment]
Kicking off another test here, and just noting that the AMQP_PASS check works :)

```
AMQP_PASS must be set and passed to the deployment, or QDR will fail to connect.
```

I got this when I used a command from history that was missing the `oc` bit from the command to pull the password inadvertently.

**Comment by leifmadsen** [comment]
Checking in after running this on Friday. I see a configuration section on the controller-0 generated like so:

```yaml
connector {
    host: default-interconnect-5671-service-telemetry.apps.stf15comm.rhos-d.infra.prod.upshift.rdu2.redhat.com
    port: 443
    role: edge
    saslPassword: pass:O0eksnFA1MeODVWBsqHV4ukqrJLF963G
    saslUsername: guest@default-interconnect
    sslProfile: sslProfile
    verifyHostname: false
}
```

I was still getting connection failures, and then started to investigate to see if the passwords were in sync, certificates in sync etc, and everything looked ok.

On a hunch I tried deleting the default-interconnect pod on the OCP deployment (STF side) and doing that caused everything to come online. Still seems that something gets generated(?) and a pod restart is required. I haven't totally reproduced this yet, and I've definitely been playing around here with Secrets and such in development/testing. Something to keep an eye on though because I've run into this twice now.

Log showing the connection failures prior to restart of the pod and then all endpoints successfully connecting and data flowing:

```
2023-11-06 14:08:41.607879 +0000 SERVER (info) [C48628] Connection to default-interconnect-5671-service-telemetry.apps.stf15comm.rhos-d.infra.prod.upshift.rdu2.redhat.com:443 failed: amqp:unauthorized-access Authentication failed [mech=PLAIN]
2023-11-06 14:08:46.772673 +0000 SERVER (info) [C48629] Connection to default-interconnect-5671-service-telemetry.apps.stf15comm.rhos-d.infra.prod.upshift.rdu2.redhat.com:443 failed: amqp:unauthorized-access Authentication failed [mech=PLAIN]
2023-11-06 14:08:51.850490 +0000 SERVER (info) [C48630] Connection to default-interconnect-5671-service-telemetry.apps.stf15comm.rhos-d.infra.prod.upshift.rdu2.redhat.com:443 failed: amqp:unauthorized-access Authentication failed [mech=PLAIN]
2023-11-06 14:08:56.924837 +0000 SERVER (info) [C48631] Connection to default-interconnect-5671-service-telemetry.apps.stf15comm.rhos-d.infra.prod.upshift.rdu2.redhat.com:443 failed: amqp:unauthorized-access Authentication failed [mech=PLAIN]
2023-11-06 14:09:02.052896 +0000 SERVER (info) [C48632] Connection to default-interconnect-5671-service-telemetry.apps.stf15comm.rhos-d.infra.prod.upshift.rdu2.redhat.com:443 failed: amqp:unauthorized-access Authentication failed [mech=PLAIN]
2023-11-06 14:09:07.471960 +0000 SERVER (info) [C48633] Connection to default-interconnect-5671-service-telemetry.apps.stf15comm.rhos-d.infra.prod.upshift.rdu2.redhat.com:443 failed: amqp:unauthorized-access Authentication failed [mech=PLAIN]
2023-11-06 14:09:07.901548 +0000 SERVER (info) [C48634] Accepted connection to 172.17.1.72:5666 from 172.17.1.72:50466
2023-11-06 14:09:07.902537 +0000 ROUTER_CORE (info) [C48634] Connection Opened: dir=in host=172.17.1.72:50466 vhost= encrypted=no auth=no user=anonymous container_id=0cff5084-8c89-4b8e-ba4f-4b1f80151dd6 props=
2023-11-06 14:09:07.903903 +0000 ROUTER_CORE (info) [C48634][L13670] Link attached: dir=in source={<none> expire:sess} target={$management expire:sess}
2023-11-06 14:09:07.908618 +0000 ROUTER_CORE (info) [C48634][L13671] Link attached: dir=out source={(dyn)<none> expire:sess} target={<none> expire:sess}
2023-11-06 14:09:07.925600 +0000 ROUTER_CORE (info) [C48634][L13670] Link lost: del=3 presett=0 psdrop=0 acc=3 rej=0 rel=0 mod=0 delay1=0 delay10=0 blocked=no
2023-11-06 14:09:07.925644 +0000 ROUTER_CORE (info) [C48634][L13671] Link lost: del=3 presett=3 psdrop=0 acc=0 rej=0 rel=0 mod=0 delay1=0 delay10=0 blocked=no
2023-11-06 14:09:07.925659 +0000 ROUTER_CORE (info) [C48634] Connection Closed
2023-11-06 14:09:12.553310 +0000 SERVER (info) [C48635] Connection to default-interconnect-5671-service-telemetry.apps.stf15comm.rhos-d.infra.prod.upshift.rdu2.redhat.com:443 failed: amqp:unauthorized-access Authentication failed [mech=PLAIN]
2023-11-06 14:09:17.695086 +0000 SERVER (info) [C48636] Connection to default-interconnect-5671-service-telemetry.apps.stf15comm.rhos-d.infra.prod.upshift.rdu2.redhat.com:443 failed: amqp:connection:framing-error SSL Failure: error:0A000126:SSL routines::unexpected eof while reading
2023-11-06 14:09:22.760705 +0000 SERVER (info) [C48637] Connection to default-interconnect-5671-service-telemetry.apps.stf15comm.rhos-d.infra.prod.upshift.rdu2.redhat.com:443 failed: amqp:connection:framing-error SSL Failure: error:0A000126:SSL routines::unexpected eof while reading
2023-11-06 14:09:27.853970 +0000 ROUTER_CORE (info) [C48638] Connection Opened: dir=out host=default-interconnect-5671-service-telemetry.apps.stf15comm.rhos-d.infra.prod.upshift.rdu2.redhat.com:443 vhost= encrypted=TLSv1.2 auth=PLAIN user=guest@default-interconnect container_id=default-interconnect-6cbf65d797-drfns props={:product="qpid-dispatch-router", :version="Red Hat AMQ Interconnect 1.10.9 (qpid-dispatch 1.14.0)", :"qd.conn-id"=2}
2023-11-06 14:09:27.854085 +0000 ROUTER_CORE (info) Edge connection (id=48638) to interior established
2023-11-06 14:09:27.854264 +0000 ROUTER_CORE (info) [C48638][L13672] Link attached: dir=out source={} target={_$qd.edge_heartbeat expire:link}
2023-11-06 14:09:27.854329 +0000 ROUTER_CORE (info) [C48638][L13673] Link attached: dir=out source={} target={_$qd.addr_lookup expire:link}
2023-11-06 14:09:27.854345 +0000 ROUTER_CORE (info) [C48638][L13674] Link attached: dir=in source={(dyn)<none> expire:link} target={}
2023-11-06 14:09:27.854363 +0000 ROUTER_CORE (info) [C48638][L13675] Link attached: dir=out source={<none> expire:link} target={<none> expire:link}
2023-11-06 14:09:27.854411 +0000 ROUTER_CORE (info) [C48638][L13676] Link attached: dir=in source={controller-0.cloud1 expire:link caps::"qd.router-edge-downlink"} target={<none> expire:link caps::"qd.router-edge-downlink"}
2023-11-06 14:09:27.854435 +0000 ROUTER_CORE (info) [C48638][L13677] Link attached: dir=in source={_$qd.edge_addr_tracking expire:link} target={<none> expire:link}
2023-11-06 14:09:27.854465 +0000 ROUTER_CORE (info) [C48638][L13678] Link attached: dir=out source={<none> expire:link} target={sensubility/cloud1-telemetry expire:link}
2023-11-06 14:09:27.854487 +0000 ROUTER_CORE (info) [C48638][L13679] Link attached: dir=out source={} target={$management expire:link}
2023-11-06 14:09:27.854517 +0000 ROUTER_CORE (info) [C48638][L13680] Link attached: dir=in source={(dyn)<none> expire:link} target={}
2023-11-06 14:09:38.856173 +0000 SERVER (info) [C48639] Accepted connection to 172.17.1.72:5666 from 172.17.1.72:47474
```

```
oc rsh default-interconnect-6cbf65d797-drfns
sh-4.2$ qdstat -c
2023-11-06 14:09:35.091370 UTC
default-interconnect-6cbf65d797-drfns

Connections
  id  host                container                             role    dir  security                                authentication                     tenant  last dlv      uptime
  ==========================================================================================================================================================================================
  1   10.129.0.1:55632    compute-1.cloud1                      edge    in   TLSv1/SSLv3(DHE-RSA-AES256-GCM-SHA384)  guest@default-interconnect(PLAIN)          000:00:00:00  000:00:00:08
  2   10.129.0.1:55640    controller-0.cloud1                   edge    in   TLSv1/SSLv3(DHE-RSA-AES256-GCM-SHA384)  guest@default-interconnect(PLAIN)          000:00:00:00  000:00:00:07
  3   10.129.0.1:55648    controller-2.cloud1                   edge    in   TLSv1/SSLv3(DHE-RSA-AES256-GCM-SHA384)  guest@default-interconnect(PLAIN)          000:00:00:00  000:00:00:07
  4   10.129.0.1:55652    compute-0.cloud1                      edge    in   TLSv1/SSLv3(DHE-RSA-AES256-GCM-SHA384)  guest@default-interconnect(PLAIN)          000:00:00:00  000:00:00:06
  5   10.129.0.1:55676    controller-1.cloud1                   edge    in   TLSv1/SSLv3(DHE-RSA-AES256-GCM-SHA384)  guest@default-interconnect(PLAIN)          000:00:00:00  000:00:00:06
  6   10.129.0.119:55472  bridge-3c0                            edge    in   no-security                             anonymous-user                             -             000:00:00:03
  7   10.129.0.118:45194  bridge-3c0                            edge    in   no-security                             anonymous-user                             -             000:00:00:03
  9   10.128.1.45:54284   bridge-342                            edge    in   no-security                             anonymous-user                             -             000:00:00:02
  8   10.128.1.44:49450   bridge-342                            edge    in   no-security                             anonymous-user                             -             000:00:00:02
  10  10.130.0.121:42348  bridge-1fe                            edge    in   no-security                             anonymous-user                             000:00:00:00  000:00:00:00
  11  127.0.0.1:33676     06ea531c-3281-4954-94f5-e393551e536a  normal  in   no-security                             no-auth                                    000:00:00:00  000:00:00:00
```

**Review by leifmadsen — APPROVED** [review]

**Comment by elfiesmelfie** [comment]
recheck

**Review by elfiesmelfie — APPROVED** [review]
The changes make sense and Leif did testing locally.

**Pull request merged**
