### PR TITLE
Pull stable operators from redhat-operators

### PR DESCRIPTION
**Pull request by mrunge**
and also stay on stable-1.2 channel

### CODE REVIEW

**Comment by mrunge** [comment]
Do you want me to drop the infrawatch-operators CatalogSource as well?

**Comment by leifmadsen** [comment]
I'm not entirely sure how I feel about this change. Changing our upstream scripts to refer to the downstream builds and releases I'm not sure makes sense here.

Personally I think I would rather see our scripts be using the latest changes from the branch, or install via the CSV directly or something.

**Comment by mrunge** [comment]
Okay, 1.2 is not installable via infrawatch-operators, and unstable does not install, see https://github.com/infrawatch/service-telemetry-operator/issues/175

**Comment by pleimer** [comment]
@mrunge unstable will fail until https://github.com/infrawatch/smart-gateway-operator/pull/72 merges

**Review by leifmadsen — CHANGES_REQUESTED** [review]
Thinking about this more, I'm going to reject this change. The script is intended to load STF from the upstream sources for testing and development, and pulling from the downstream released version doesn't help accomplish that.

If you need a released/stable version of STF, then you should install via the official documentation and consume it via the redhat-operators catalog. If the issue is that things are not working, then we should resolve the problem.

**Comment by mrunge** [comment]
How are you then testing stable upstream changes, if 1.2 from upstream does not install, and unstable fails to install as well?

**Comment by leifmadsen** [comment]
> How are you then testing stable upstream changes, if 1.2 from upstream does not install, and unstable fails to install as well?

Installing from CSV directly I guess. I am not testing it currently, but that doesn't mean it shouldn't be fixed. My focus has been on downstream release and release management along with being injured. It'll be fixed when it's fixed, but just circumventing the upstream to pull the downstream is not a solution here.

**Comment by mrunge** [comment]
Yeah, I would prefer using upstream first.

**Comment by leifmadsen** [comment]
> Yeah, I would prefer using upstream first.

Sure that makes sense, but sometimes it'll be in a broken state, and will need to be rescued. It is what it is. Anyways, I'm going to close this for now. I'd suggest just importing the CSVs directly or using the downstream release for now until I can get time to do another upstream release.

**Comment by mrunge** [comment]
broken state is okay for unstable, but not for stable branches, imho.

**Comment by leifmadsen** [comment]
I agree, but I can only do so much. Interested in creating new bundles and index images?

**Pull request closed without merging**
